[package]
name = "rust-based-test-lang"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_more = { version = "1.0.0", features = ["from", "into"] }
pest = "2.7.11"
pest_derive = "2.7.11"

[dev-dependencies]
similar-asserts = "1.5.0"
