name: Rust build & check

on:
  push

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: cargo check
    - run: cargo clippy -- -D warnings
    - name: Build
      run: cargo build --all-features
    - name: Run tests
      run: cargo test --no-fail-fast --all-features
